CREATE TABLE IF NOT EXISTS mpas (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa VARCHAR
);

CREATE TABLE IF NOT EXISTS films (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    id_mpa int REFERENCES mpas,
    release_date date,
    duration int
);

CREATE TABLE IF NOT EXISTS genres (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar
);

CREATE TABLE IF NOT EXISTS users (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    email varchar,
    login  varchar,
    birthday date
);


CREATE TABLE IF NOT EXISTS genres_and_films (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_film long REFERENCES films,
    id_genre long REFERENCES genres
);

CREATE TABLE IF NOT EXISTS likes (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_film long REFERENCES films,
    id_user long REFERENCES users
);

CREATE TABLE IF NOT EXISTS friends (
    id_user long,
    id_friend_user long,
    is_confirmed boolean,

    CONSTRAINT user_friend_id_pk
    PRIMARY KEY (id_user, id_friend_user),

    CONSTRAINT fk_id_user
    FOREIGN KEY (id_user)
    REFERENCES users
    ON DELETE CASCADE,

    CONSTRAINT fk_id_friend_user
    FOREIGN KEY (id_friend_user)
    REFERENCES users
    ON DELETE CASCADE
);