CREATE TABLE IF NOT EXISTS mpas (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    id_mpa int REFERENCES mpas,
    release_date date,
    duration int
);

CREATE TABLE IF NOT EXISTS users (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    email varchar,
    login  varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friends (
    id_user long,
    id_friend_user long,
    is_confirmed boolean,

    CONSTRAINT user_friend_id_pk
    PRIMARY KEY (id_user, id_friend_user),

    CONSTRAINT fk_id_user
    FOREIGN KEY (id_user)
    REFERENCES users
    ON DELETE CASCADE,

    CONSTRAINT fk_id_friend_user
    FOREIGN KEY (id_friend_user)
    REFERENCES users
    ON DELETE CASCADE
    );


CREATE TABLE IF NOT EXISTS genres_and_films (
    id_film long,
    id_genre long,

    CONSTRAINT genres_and_films_pk
    PRIMARY KEY (id_film, id_genre),

    CONSTRAINT fk_id_film
    FOREIGN KEY (id_film)
    REFERENCES films
    ON DELETE CASCADE,

    CONSTRAINT fk_id_genre
    FOREIGN KEY (id_genre)
    REFERENCES genres
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
    id_film long,
    id_user long,

    CONSTRAINT fk_id_film_likes
    FOREIGN KEY (id_film)
    REFERENCES films
    ON DELETE CASCADE,

    CONSTRAINT fk_id_user_likes
    FOREIGN KEY (id_user)
    REFERENCES users
    ON DELETE CASCADE
);
